# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 300)
        Form.setMinimumSize(QtCore.QSize(500, 300))
        Form.setMaximumSize(QtCore.QSize(500, 300))
        Form.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 50, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 6pt \"Arial\";\n"
"font: 75 italic 8pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.edit_username = QtWidgets.QLineEdit(Form)
        self.edit_username.setGeometry(QtCore.QRect(180, 100, 113, 20))
        self.edit_username.setObjectName("edit_username")
        self.edit_password = QtWidgets.QLineEdit(Form)
        self.edit_password.setGeometry(QtCore.QRect(180, 150, 113, 20))
        self.edit_password.setObjectName("edit_password")
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.btn_login.setObjectName("btn_login")
        self.btn_regeist = QtWidgets.QPushButton(Form)
        self.btn_regeist.setGeometry(QtCore.QRect(410, 260, 75, 23))
        self.btn_regeist.setObjectName("btn_regeist")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.label_2.setText(_translate("Form", "LOGIN"))
        self.edit_username.setPlaceholderText(_translate("Form", "用户名"))
        self.edit_password.setPlaceholderText(_translate("Form", "密码"))
        self.btn_login.setText(_translate("Form", "登录"))
        self.btn_regeist.setText(_translate("Form", "注册"))
